version: '3.1'

services:
  app:
    image: node
    ports:
      - 4200:4200
    volumes:
    - ./app:/src
    working_dir: '/src'
    command: 'sh ./start.sh'
    depends_on:
      - node
  node:
    image: node
    ports:
      - 3000:3000
    volumes:
      - ./shop-api:/src
    depends_on:
      - mysql
    working_dir: '/src'
    command: 'sh ./start.sh'
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
